# CMake generated Testfile for 
# Source directory: /var/www/opencv/modules
# Build directory: /var/www/opencv/rebuild/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(calib3d/.calib3d)
SUBDIRS(core/.core)
SUBDIRS(cudaarithm/.cudaarithm)
SUBDIRS(cudabgsegm/.cudabgsegm)
SUBDIRS(cudacodec/.cudacodec)
SUBDIRS(cudafeatures2d/.cudafeatures2d)
SUBDIRS(cudafilters/.cudafilters)
SUBDIRS(cudaimgproc/.cudaimgproc)
SUBDIRS(cudalegacy/.cudalegacy)
SUBDIRS(cudaobjdetect/.cudaobjdetect)
SUBDIRS(cudaoptflow/.cudaoptflow)
SUBDIRS(cudastereo/.cudastereo)
SUBDIRS(cudawarping/.cudawarping)
SUBDIRS(cudev/.cudev)
SUBDIRS(features2d/.features2d)
SUBDIRS(flann/.flann)
SUBDIRS(highgui/.highgui)
SUBDIRS(imgcodecs/.imgcodecs)
SUBDIRS(imgproc/.imgproc)
SUBDIRS(java/.java)
SUBDIRS(ml/.ml)
SUBDIRS(objdetect/.objdetect)
SUBDIRS(photo/.photo)
SUBDIRS(python/.python)
SUBDIRS(shape/.shape)
SUBDIRS(stitching/.stitching)
SUBDIRS(superres/.superres)
SUBDIRS(ts/.ts)
SUBDIRS(video/.video)
SUBDIRS(videoio/.videoio)
SUBDIRS(videostab/.videostab)
SUBDIRS(viz/.viz)
SUBDIRS(world/.world)
SUBDIRS(core)
SUBDIRS(flann)
SUBDIRS(imgproc)
SUBDIRS(ml)
SUBDIRS(objdetect)
SUBDIRS(photo)
SUBDIRS(video)
SUBDIRS(imgcodecs)
SUBDIRS(shape)
SUBDIRS(videoio)
SUBDIRS(highgui)
SUBDIRS(superres)
SUBDIRS(ts)
SUBDIRS(features2d)
SUBDIRS(calib3d)
SUBDIRS(java)
SUBDIRS(stitching)
SUBDIRS(videostab)
SUBDIRS(python2)
